# Railway configuration for Indian Event Manager Backend

[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHON_VERSION = "3.9"

# Environment variables will be set in Railway Dashboard
# Required variables:
# - DATABASE_URL
# - SECRET_KEY
# - ALLOWED_HOSTS
# - CORS_ORIGINS
# - ACCESS_TOKEN_EXPIRE_MINUTES
# - ENVIRONMENT (production)

[[services]]
name = "web"
envVars = [
    "DATABASE_URL",
    "SECRET_KEY",
    "ALLOWED_HOSTS",
    "CORS_ORIGINS",
    "ACCESS_TOKEN_EXPIRE_MINUTES",
    "ENVIRONMENT"
]

[[services.ports]]
port = "$PORT"
internal = false
