services:
  - type: web
    name: indian-event-manager-api
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      chmod +x startup.sh
    startCommand: ./startup.sh
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: postgres://indian_event_manager_user:StkZYHs55ID7fDAQrTO4tMzdE0eGwqeo@dpg-cu9j7b3qf0us73c81in0-a.oregon-postgres.render.com/indian_event_manager
      - key: SECRET_KEY
        value: DxvVnmQ0wFdZBwNcmyawYEISCpdos-1PhcRc1wf20PU
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_HOSTS
        value: '["indian-event-manager.onrender.com"]'
      - key: CORS_ORIGINS
        value: '["https://indian-event-manager.vercel.app", "https://indian-event-manager-6g6m331f4-vics-projects-31447d42.vercel.app"]'
      - key: MAX_UPLOAD_SIZE
        value: "5242880"
      - key: UPLOAD_DIR
        value: static/uploads
    disk:
      name: uploads
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1
