export enum UserRole {
  USER = "USER",
  ADMIN = "ADMIN",
  SPONSOR = "SPONSOR",
  ORGANIZER = "ORGANIZER"
}

export enum AdminLevel {
  BASIC = "BASIC",
  MANAGER = "MANAGER",
  SUPER_ADMIN = "SUPER_ADMIN"
}

export enum AdminPermission {
  VIEW_DASHBOARD = "VIEW_DASHBOARD",
  MANAGE_USERS = "MANAGE_USERS",
  MANAGE_EVENTS = "MANAGE_EVENTS",
  MANAGE_SPONSORS = "MANAGE_SPONSORS",
  MANAGE_SETTINGS = "MANAGE_SETTINGS",
  VIEW_AUDIT_LOGS = "VIEW_AUDIT_LOGS",
  MANAGE_MARKETING = "MANAGE_MARKETING"
}
