name: Deploy to Vercel
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: prj_AMm1pcJDev8bbA0mcYbc8VqwW8p6
          VERCEL_ORG_ID: team_6aukAhEK81l3Px1oyq2pHaiV

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: prj_AMm1pcJDev8bbA0mcYbc8VqwW8p6
          VERCEL_ORG_ID: team_6aukAhEK81l3Px1oyq2pHaiV

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: prj_AMm1pcJDev8bbA0mcYbc8VqwW8p6
          VERCEL_ORG_ID: team_6aukAhEK81l3Px1oyq2pHaiV
